### PR TITLE
Update meteor

### PR DESCRIPTION
**Pull request by elGatoMantocko**
1.2.1 doesn't bring any breaking changes. Bumping up packages for improved ES support.

It also looks like it could possibly help with memory issues. I haven't confirmed this yet though.

### CODE REVIEW

**Comment by elGatoMantocko** [comment]
Looks like this will probably be a no merge. Upgrading breaks all of the cuke tests.

**Comment by elGatoMantocko** [comment]
https://github.com/xolvio/chimp/pull/141 solved the problem

**Comment by elGatoMantocko** [comment]
After more usage, leaving the server to run overnight, and extensive editing while letting it run, it looks like the memory usage is a lot better. Just something to keep in mind.

**Comment by cjsauer** [comment]
:+1:

**Comment by marti584** [comment]
:+1:

**Pull request merged**
