### PR TITLE
New channel page

### PR DESCRIPTION
**Pull request by elGatoMantocko**
### Things I did:

- implement new channel form on /channels/new
- validate that the fields aren't empty
- wrote test case for valid channel

### Notes:
It looks like I have to click twice on submit to actually submit the channel. It could be because of the error catching, but i am not sure. Could use some more investigation. 

I will also write another test scenario or two to make sure that the validation process works.

### CODE REVIEW

**Comment by marti584** [comment]
:+1:

**Comment by elGatoMantocko** [comment]
:+1:

**Comment by marti584** [comment]
:+1: again

**Comment by elGatoMantocko** [comment]
Thank god for https://github.com/jagi/meteor-astronomy/issues/71. That issue saved my life on this one!

**Comment by marti584** [comment]
This looks good now.

**Comment by cjsauer** [comment]
This is looking really good. Only thing I see is that your test to make sure you're on the new channel isn't quite strong enough. I think if you displayed the actual title and query on the page and asserted their existence it'd be stronger. 

Other than that :+1:

**Comment by elGatoMantocko** [comment]
So I have given it some thought and I don't think I will make the test any stronger for this PR. If I do then I think I am starting to get a little off topic. The channel page is going to be a decent amount of work in itself i think and I would prefer to leave any channel page topics in its own branch.

So here is my :+1: and I am going to merge.

**Comment by cjsauer** [comment]
Up to you. I was thinking that right now you're not proving that what you submitted is actually creating a channel at all. I'd say that's pretty on topic for this branch. The channel page doesn't have to be finished, it just has to show that it actually is in the database.

**Pull request merged**
