### PR TITLE
Hotfixes, security, removing subscribe-related stuff

### PR DESCRIPTION
**Pull request by cjsauer**
### What I did:

+ Moved getUrls into a server only method, because it depends on an NPM package that won't be available to the client
+ Removed any tests related to subscribing, and fixed the ones that remain (async issues)
+ Added a blank route to the fixtures package. This makes the testing of publications much easier, as there won't be any conflicting publications on the page already.
+ Deny any editing to the User's profile field. For some reason in Meteor it is the default to allow *any* editing to the user profile field.

### CODE REVIEW

**Comment by marti584** [comment]
:+1:

**Comment by marti584** [comment]
:hamster:

**Comment by cjsauer** [comment]
:dango:

**Comment by elGatoMantocko** [comment]
:fist: :+1:

**Comment by elGatoMantocko** [comment]
RIP Circle

**Comment by marti584** [comment]
RIP :red_circle:

**Comment by cjsauer** [comment]
:boom:

**Pull request merged**
