### PR TITLE
Home page and navbar

### PR DESCRIPTION
**Pull request by elGatoMantocko**
### Things I did
- List off channels on the home page
- Test that the channels can be seen

### What's left
- ~~I need to make sure the href of the list group elements points to /channels/_id~~
- ~~Test that clicking on those channels redirects~~
- ~~I was thinking about adding a click event to turn the .list-group-item active when clicked but I am not sure if it is worth it because the page with redirect to the channel~~

### CODE REVIEW

**Comment by elGatoMantocko** [comment]
Because #11 and #12 share some dependencies with each other (creating a new channel then visualizing the channel) I will likely have to write some more explicit tests. It's probably important that I test the functionality of the modules together.

**Comment by cjsauer** [comment]
Couple comments: you're registering a subscription in the home route. I thought that was decided to be an [anti pattern in Flow](https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management). He explains why in that guide. 

In your tests, you're waiting for an element with class .list-group. I think you should give those elements a much more specific class like .channel-group. That way it won't conflict with a list somewhere else on the page and unexpectedly fail our tests.

**Comment by elGatoMantocko** [comment]
My bad. Should be fixed now.

**Comment by cjsauer** [comment]
:+1:

**Comment by marti584** [comment]
:+1:

**Pull request merged**
